import { generateStructured } from "@/lib/ai/client";
import { buildBusinessContext, GROUNDING_RULES } from "@/lib/ai/prompts";
import { seoPlanSchema } from "@/lib/ai/schemas";
import type { BusinessProfile } from "@/lib/types";
import type { z } from "zod";
import type { contentFilledPagesSchema } from "@/lib/ai/schemas";

type ContentFilledPages = z.infer<typeof contentFilledPagesSchema>;

/**
 * Generates title/meta description per page and site-wide SEO defaults.
 * Structured data, sitemap.xml and robots.txt are derived deterministically
 * from the persisted pages (see src/app/s/[slug]/sitemap.xml) rather than
 * generated by the model, since they must always exactly match the site.
 */
export class SEOGenerator {
  async generate(profile: BusinessProfile, pages: ContentFilledPages["pages"]) {
    return generateStructured({
      schema: seoPlanSchema,
      temperature: 0.4,
      system: `Tu es un expert SEO local pour PME.
${GROUNDING_RULES}
Génère un title (≤ 60 caractères idéalement, max 70) et une meta description (≤ 155 caractères idéalement, max 180) par page, optimisés pour la recherche locale/sectorielle, sans mots-clés forcés ni promesses non vérifiables.
Réponds avec un JSON : {"global_seo": {"site_title": string, "site_description": string}, "pages": [{"slug": string, "seo": {"title": string, "description": string}}]}`,
      user: `Profil business :\n${buildBusinessContext(profile)}\n\nPages du site :\n${JSON.stringify(
        pages.map((p) => ({ slug: p.slug, title: p.title, is_home: p.is_home })),
        null,
        2,
      )}`,
    });
  }
}
